formatter: markdown
header-from: .header.md
content: |-
  {{ .Header }}

  ## Usage
settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true